import Logo from "@/components/logo";
import type { Metadata } from "next";


import Themegenerator from "@/components/Themegenerator";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col h-screen min-w-screen max-h-screen">
      <nav className="w-full flex h-[60px] p-6 border-b border-border items-center justify-between ">
        <Logo />
   
          <Themegenerator />
          
    
      </nav>
      <main className="flex width-full grow">{children}</main>
    </div>
  );
}