import Logo from "../../components/Logo";
import type { Metadata } from "next";
import Themegenerator from "./../../components/Themegenerator";
import { UserButton } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col min-h-screen min-w-screen max-h-screen">
      <nav className="w-full flex h-[60px] p-6 border-b border-border items-center justify-between ">
        <Logo />
        <div className="flex gap-2 items-center justify-center">
          <Themegenerator />
          <UserButton afterSignOutUrl="/sign-in" />
        </div>
      </nav>
      <main className="flex wifull grow">{children}</main>
    </div>
  );
}
